"""Serialize a mapped artifact into the fixed-width TXT and JSON summary."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from serialization import serialize_mapped_artifact_to_txt


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Read a mapped artifact, generate the 43-character TXT and persist a serialization summary."
    )
    parser.add_argument(
        "--mapped",
        type=Path,
        required=True,
        help="Mapped artifact JSON generated by the mapping stage.",
    )
    parser.add_argument(
        "--txt-output",
        type=Path,
        default=None,
        help="Optional TXT output path. When omitted, it is derived from the mapped artifact path.",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=None,
        help="Optional JSON summary output path. When omitted, it is derived from the mapped artifact path.",
    )
    args = parser.parse_args()

    artifacts = serialize_mapped_artifact_to_txt(
        args.mapped,
        txt_path=args.txt_output,
        summary_path=args.summary_output,
    )
    print(
        " ".join(
            [
                f"serializadas={len(artifacts.result.serialized_lines)}",
                f"nao_serializadas={len(artifacts.result.skipped_items)}",
                f"txt={artifacts.txt_path}",
                f"resumo={artifacts.summary_path}",
            ]
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

