"""Validate and reconcile the V1 pipeline artifacts end to end."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from validation import validate_pipeline_v1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Read snapshot, mapped artifact, TXT and serialization summary and persist a final validation artifact."
    )
    parser.add_argument("--snapshot", type=Path, required=True, help="Canonical ingestion snapshot JSON.")
    parser.add_argument("--mapped", type=Path, required=True, help="Mapped artifact JSON.")
    parser.add_argument("--txt", type=Path, required=True, help="Fixed-width TXT generated by serialization.")
    parser.add_argument(
        "--serialization-summary",
        type=Path,
        required=True,
        help="JSON summary generated by the serialization stage.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional validation artifact path. When omitted, it is derived from the TXT path.",
    )
    args = parser.parse_args()

    artifacts = validate_pipeline_v1(
        snapshot_path=args.snapshot,
        mapped_artifact_path=args.mapped,
        txt_path=args.txt,
        serialization_summary_path=args.serialization_summary,
        output_path=args.output,
    )
    print(
        " ".join(
            [
                f"status={artifacts.result.status.value}",
                f"fatal={len(artifacts.result.fatal_errors)}",
                f"inconsistencias={len(artifacts.result.inconsistencies)}",
                f"warnings={len(artifacts.result.warnings)}",
                f"saida={artifacts.output_path}",
            ]
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

